### ISSUE TITLE
juju_application and juju_unit labels are incorrect and confusing

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-proxy-operator#134]
### Bug Description

I suspect that this issue was caused by https://github.com/canonical/cos-proxy-operator/pull/120 and other related patches.

When using cos-proxy rev 74, `juju_application` shows incorrect/confusing labels, for example:
- nagios context in nrpe is set to `bootstack-blue`
- hostname is `abc1-cloud-node-5`
- application name is `nova-compute-kvm`
- unit name is `nova-compute-kvm/2`

The expected labels and the previous behaviour of cos-proxy are:
- `juju_unit="nova-compute-kvm/2"`
- `juju_application="nova-compute-kvm"`

In the recent versions of cos-proxy it became:
- `juju_unit="bootstack-blue-abc1-cloud-node/5"`
- `juju_application="bootstack-blue-abc1-cloud-node"`

Neither is correct since such a Juju application and unit don't exist.

The charm seems to make an incorrect assumption that the hostname always matches the juju unit name which almost never happens.

### To Reproduce

1. Deploy cos-proxy rev 74.
2. Deploy `ch:ubuntu` as `ubuntu` app to a VM with its hostname set to `abc-123`.
3. Deploy `nrpe` charm as a subordinate to `ubuntu`. Set any nagios_context.
4. Set up `monitors` relation, relate cos-proxy to COS as always.
5. In prometheus and alertmanager, the `juju_application` and `juju_units` labels will show `<nagios_context>-abc` and `abc/123` incorrectly.

### Environment

cos-proxy rev 74, other versions shouldn't matter

### Relevant log output

```shell
None, the labels in Prometheus/Alertmanager are incorrect.
```

**Comment by mmkay** [comment]
This should be rolled back to the previous behaviour. Hostname should be a separate label.

**Comment by sed-i** [comment]
- According to @przemeklal, rev 54 behaves differently, "more correctly", and that in rev 71 the labels are already "wrong".
- @przemeklal also noted that if the hostnames don't follow the "abc-123" pattern but something like to a-abc123 (i.e. do not end with `-` and number), then both juju_application and juju_unit labels are identical and equal to the hostname.
- Inspecting the [rev54...rev71 diff](https://github.com/canonical/cos-proxy-operator/compare/rev54...rev71), I see no functional difference for `lib/charms/nrpe_exporter/v0/nrpe_exporter.py`.

## To reproduce

### Relation view

```mermaid
flowchart LR

subgraph VM model
nova-compute-kvm --- nrpe --- cos-proxy
end

subgraph COS
prometheus
end

cos-proxy --- prometheus
```

### Machine view
```mermaid
graph TD

subgraph "Machine: some-nice-hostname"

subgraph "Subordinates"
nrpe/0
end

nrpe/0 --- cos-proxy/0
nova-compute-kvm/2 --- nrpe/0

end
```

I wonder if this is because multiple charms are deployed on the same machine (`juju deploy --to`). I would compare labels to when the machine is named after the charm, and cos-proxy is in its own vm.

---

Somewhat related: https://github.com/canonical/grafana-agent-operator/pull/63

**Comment by Abuelodelanada** [comment]
Well, seems I've found the issue....

I have the following deployment:

![image](https://github.com/canonical/cos-proxy-operator/assets/939888/2724d0c7-c8fe-448a-9bcb-c994eae7013c)


With the following config in `nrpe`:

```
juju config nrpe nagios_host_context="bootstack-blue"
```


Once every relation is in place, I can see in Prometheus:

![image](https://github.com/canonical/cos-proxy-operator/assets/939888/1c428ea8-a92b-49eb-914b-4990a7d3ffc7)

We have a bug in the way we create the `relabels_config` list:

```python
                "relabel_configs": [
                    {"source_labels": ["__address__"], "target_label": "__param_target"},
                    {"source_labels": ["__param_target"], "target_label": "instance"},
                    {"source_labels": ["__param_command"], "target_label": "command"},
                    {
                        "target_label": "__address__",
                        "replacement": "{}:9275".format(exporter_address),
                    },
                    {
                        "target_label": "juju_unit",
                        # Turn sql-foo-0 or redis_bar_1 into sql-foo/0 or redis-bar/1
                        "replacement": re.sub(r"^(.*?)[-_](\d+)$", r"\1/\2", id.replace("_", "-")),
                    },
                ],
```

The problem is that we relabel the `juju_unit` by using the [`target-id`](https://github.com/canonical/charm-nrpe/blob/master/hooks/nrpe_helpers.py#L271) that is stored in the relation data by the `nrpe` charm. Besides, the `nrpe` charm concatenates the `unit` name with the `nagios_host_context`


```python
(Pdb) relation.data
{..., 'target-id': 'bootstack-blue-nova-compute-kvm-0'}, <ops.model.Application nrpe>: {}}
```

that's why `juju_unit` label ends up being `bootstack-blue-nova-compute-kvm/0`


At this point we should:

1. Figure out a way to get the `unit.name` from `bootstack-blue-nova-compute-kvm/0`
2. Add a new relabel config for `juju_application`.

**Comment by Abuelodelanada** [comment]
Hi @peppepetra 

Do you think is it possible to add `nagios_host_context` as a field in [nrpe relation databag](https://github.com/canonical/charm-nrpe/blob/master/hooks/nrpe_helpers.py#L270) so we can use it to discover `juju_application` and `juju_unit`??
