### ISSUE TITLE
Add dns_name of the target to the labels of metrics added to prometheus-k8s via cos-proxy

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-proxy-operator#32]
### Enhancement Proposal

The legacy [charm promtheus2](https://charmhub.io/prometheus2)  add a label "dns_name" [0] which is used by many dashboards to correlate metrics from different targets. This label is missing when adding targets to prometheus-k8s via cos-proxy breaking the existing dashboards. It would be good if this label can be added by cos-proxy as well to ensure compatibility with existing dashboards.

0. https://git.launchpad.net/charm-prometheus2/tree/src/reactive/prometheus.py#n722

**Comment by rbarry82** [comment]
This is theoretically possible, but is liable to be unstable/unreliable. There is no meaningful way that we can ensure that the DNS resolver inside k8s for COS in an external model (and hopefully external controller/host) will be able to perform a successful DNS lookup on any given hostname.

Instead, if you can give an example dashboard, we're better off culling it out, and waiting for the `grafana-agent` machine charm to be available, which _will_ be able to be deployed on the edge (like `cos-proxy`) and do this. Arbitrarily, the Prometheus [`static_config` block](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config) probably could look this up and set it as a label, but I'd love to see an example of a dashboard where it's used. @simskij thoughts?

**Comment by peppepetra** [comment]
@rbarry82 I understand the challenge, but if cos-proxy won't provide a way to transparently reuse the existing features of the legacy LMA, it feels like it is failing to achieve its purpose and we will need to rewrite dashboards and exporters instead of using cos-proxy.

An example of dashboards using it are the ones provided by the prometheus-openstack-exporter charm [0] that mix together in two dashboards data from prometheus-openstack-exporter, prometheus-libvirt-exporter and telegraf, and to do so use the dns_name to correlate the metrics.

0. https://git.launchpad.net/charm-prometheus-openstack-exporter/tree/src/templates/grafana-dashboards

**Comment by rbarry82** [comment]
> @rbarry82 I understand the challenge, but if cos-proxy won't provide a way to transparently reuse the existing features of the legacy LMA, it feels like it is failing to achieve its purpose and we will need to rewrite dashboards and exporters instead of using cos-proxy.

The goal of `cos-proxy` is not to transparently re-use _all_ the existing features of the existing LMA. There are some which we will never add. For example, having [pre-baked dashboards for some services](https://git.launchpad.net/charm-grafana/tree/src/templates/dashboards/prometheus) which are [generated on-demand by literally querying Prometheus to discover whether it knows about those metrics](https://git.launchpad.net/charm-grafana/tree/src/reactive/grafana.py#n1004). 

Similarly, a better workaround here would simply be for `cos-proxy` to edit the dashboard JSON before forwarding it and replace `dns_name` with [`host`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L2211), or have another relabel config which [keeps `instance`](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L2233) and substitute that in the dashboards.

The purpose of `cos-proxy` is to do _those kinds_ of transformations so can be continued to be used, as similarly as possible, until, yes, dashboards and exporters are rewritten.

Very simply, doing a DNS lookup from something which could be a cross-model relation (and we have no real way to detect or stop that) could result in almost any behavior. If a charm is providing a dashboard which expects a "valid" `dns_name` to actually perform that step (and provide a resolved label value) _itself_ rather than inverting control. Eventually, rewriting dashboards and exporters will actually be needed to perform operations exactly as the one you're describing. We are happy to help do so, and provide workarounds in the meantime, but the workarounds will be just that -- some of them will not be 1:1 re-implementations of the way legacy LMA charms do things.
 
> Examples of dashboards using dns_name are the ones provided by the prometheus-openstack-exporter charm [0] that mix together in two dashboards data from prometheus-openstack-exporter, prometheus-libvirt-exporter and telegraf, and to do so use the dns_name to correlate the metrics.
> 
> 0. https://git.launchpad.net/charm-prometheus-openstack-exporter/tree/src/templates/grafana-dashboards

Based on these queries, either of the options above (rewriting the dashboard to use `host`, though that's used in many dashboards, so a different relabeling may be desired) are sustainable, maintainable stopgaps. Do you have a preference?

**Comment by aieri** [comment]
> Very simply, doing a DNS lookup from something which could be a cross-model relation (and we have no real way to detect or stop that) could result in almost any behavior.

FTR prometheus2 is usually deployed in a separate lma model compared to where the metrics sources are located, so it is already the case that those dns_lookups could return pretty much anything. It's not a great solution and we should move away from it; at the same time I see cos-proxy in itself as a stopgap solution, only meant to enable a gradual transition from the legacy LMA stack to the COS. Once everything will have been rewritten we will no longer need cos-proxy and we'll be able to deprecate it. As such, I feel that pragmatic imperfect workarounds are ok in the cos-proxy charm.

I'll let Giuseppe comment on which relabeling workaround would be most appropriate. I will be happy with anything that lets us move to the COS sooner.

**Comment by rbarry82** [comment]
That's sort-of the concern with adding it -- that it could return pretty much anything. And while `cos-proxy` may be able to be deprecated for some use cases, there may be other users down the line who are... less happy with compromises which yield unpredictable behavior (like `dns_name` not _actually_ being a DNS name). 

There's already enough confusion about "why can't I establish a cross-mode/cross-controller relation to one inside microk8s" (bootstrapping with `public-dns-address=...` and/or `controller-external-ips=...` is non-obvious), and "ok, we'll relabel this or mangle the field in the dashboard so it keeps working, but it won't _actually_ be DNS with all of the caveats around lookups that implies".

Sure, in the long run, targets should set this label themselves. And in the short term, we absolutely will provide a workaround. I just wanted to be clear that it _would_ be a workaround (and not trying DNS lookups ourselves), and that some of the "other" functionality of legacy LMA (pre-baked dashboards in Grafana) will probably never be supported either.

As with this, we're happy to provide or help with bridge/stopgap solutions, just trying to steer clear of Hyrum's Law.

**Comment by rbarry82** [comment]
Closed as part of #31
