### ISSUE TITLE
Add support for the `prometheus-manual` interface

### ISSUE THREAD

**Issue by simskij** [canonical/cos-proxy-operator#41]
### Enhancement Proposal

Used for instance by the [Kubernetes control plane](https://github.com/charmed-kubernetes/charm-kubernetes-control-plane/blob/b5adc61801cd227e492db69f8c7ebacd8b903464/metadata.yaml#L44), among others.

**Comment by rbarry82** [comment]
@stonepreston @Cynerva -- tagging you both since you committed to that repo recently.

Can you post contents of what's in the relation databag, so we know whether this is another "normal" prometheus interface with a different name, or a 3rd (so far) reactive prometheus relation which is slightly different?

I don't have an environment to set up charmed k8s

**Comment by Cynerva** [comment]
I have some time today, I'll give it a go.

**Comment by Cynerva** [comment]
Output from `juju show-unit` on a lazy test charm related to kubernetes-control-plane:prometheus, which shows the relation data coming from kubernetes-control-plane: [link](https://paste.ubuntu.com/p/77bM78TvcC/)

The kubernetes-control-plane charm calls prometheus.register_job here: [link](https://github.com/charmed-kubernetes/charm-kubernetes-control-plane/blob/ce3c9a1db9d31b999eba0875d65c39efb065bd13/reactive/kubernetes_control_plane.py#L3515-L3530)

prometheus.register_job is defined in the reactive interface implemention here: [link](https://github.com/juju-solutions/interface-prometheus-manual/blob/51094180f38de3e66afcda5e520cd0b895e88c26/provides.py#L17)

**Comment by rbarry82** [comment]
Thanks! The `register_job` stuff doesn't actually matter to us (from an OF point of view, establishing the relation on the correct interface name is good enough for the reactive libs to start talking, and the templating is done on the k8s side).

This is definitely different from the other interfaces, but on the upside, it's more or less just standard job definitions instead of "here's a scrape endpoint, figure it out yourself". This will be new development work, since we don't have anything existing like it in the proxy, and the closest we get in k8s world is `prometheus-scrape-target-k8s-operator` (which could _almost_ take this as-is, but not quite), but it looks really easy to work with.
