### ISSUE TITLE
Monitors relation takes long time to settle.

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-proxy-operator#56]
### Bug Description

In an environment with > 2k nrpe checks and 196 nrpe units, cos-proxy is still executing `monitors-relation-joined` and `monitors-relation-changed` after more than 24 hours.

It seems that there are rooms to improve efficiency of those hooks.

### To Reproduce

Relate cos-proxy with nrpe:monitors in an environment with ~ 200 nrpe units

### Environment

cos-proxy rev. 33 channel edge

### Relevant log output

```shell
unit-cos-proxy-monitors-0: 14:33:24 INFO juju.worker.uniter.operation ran "monitors-relation-changed" hook (via hook dispatching script: dispatch)
unit-cos-proxy-monitors-0: 14:33:24 INFO juju.worker.uniter.operation ran "monitors-relation-joined" hook (via hook dispatching script: dispatch)
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:25 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
unit-cos-proxy-monitors-0: 14:33:26 WARNING unit.cos-proxy-monitors/0.juju-log monitors:788: Monitor data is not a dict after parsing. Skipping.
```

**Comment by rbarry82** [comment]
I'm not _entirely_ sure whether I'll be able to deploy an environment quite large enough to duplicate this, but if you can give an example of some charm (hopefully one without too many deps, which can be deployed on LXD -- having a machine with 128GB/64 cores is great, but 175+ instances of some database may still clog it). May be something we need to look at during a shared time window.

The library in the exporter itself is reasonably efficient. Reasonably. It would be interesting to know whether the same message was coming through the whole time, and even relative CPU/memory load.

Because we are "fanning in" relations, and don't want a single new NRPE to accidentally wipe the old ones, each `relation-changed` event [iterates through _every_ relation](https://github.com/canonical/cos-proxy-operator/blob/efa0891d052def4e77e33b922cebaff5074b4ea2/lib/charms/nrpe_exporter/v0/nrpe_exporter.py#L290) to build a list of what _should_ be there, compares it to stored values from the last time a hook came through to get a list of which ones are no longer valid, and sends it back.

From there, it gets tricky:
* For every removed target or alert (if any), they are [removed from the relation databag for Prometheus](https://github.com/canonical/cos-proxy-operator/blob/main/src/charm.py#L416). 
* Then, the "enrichment file" of CSV data containing additional information to amend NRPE logs is tweaked (this should be pretty fast, because Python's CSV module is optimized, but it's still disk -- incidentally, `watch -n 3 'wc -l /etc/vector/nrpe_lookup.csv'` will provide a more or less immediate count of how many have been processed so far)
* The list of valid/current NRPE endpoints/scrape jobs and alert rules are [added to Prometheus](https://github.com/canonical/cos-proxy-operator/blob/main/src/charm.py#L430). 

There is very likely room for optimization there, because there are no methods for "batched" updates. Every individual monitor change is individual, though, thanks to Juju. We don't really know how many relation events may be "pending" to just pop them off the stack until we get to the last one, knowing that _that_ will be the data we want.

Since we're sending everything to Prom, the logic must be careful to also _not_ wipe, say, Telegraf or other `prometheus-client|prometheus-rules` data, and each relation event which comes through must, in turn, do the same thing. The nature of relation data is basically that _all_ of the alert rules and metrics "fanned" through the proxy go into a single bucket, because the old/reactive `req_...` model for semi-temporary relation data/events which rapidly make `juju show-X` unusable isn't really there.

My gut feeling is that the time spent in the "event" storm is there. Not even in the `nrpe_exporter` library, but in "ok, another `relation-changed` event -- go get the data we gave to prometheus, see if this target/rule is present and identical, if it isn't, add it to the list/dict, and set relation data", and that's really, annoyingly, incredibly hard to avoid.

A read-through of `MetricsEndpointAggregator` looks like this would take a smallish patch, but the best workaround (and long-term fix, if the cause is what my gut feeling says it is) will probably be "relate the proxy to the NRPEs first and let it settle, _then_ relate to Prometheus". After the patch to make that flow nicer, anyway

**Comment by Abuelodelanada** [comment]
We will document a workaround to deploy such large scale scenarios:

- First relate the workloads to COS-Proxy
- Wait for them to settle
- Then relate to COS-Lite

**Comment by jeffreychang911** [comment]
Hi, 
Solutions QA see this in most of our runs recently, one [run](https://solutions.qa.canonical.com/testruns/fdbc1ff6-0960-483b-a9a8-054bb3892978) here. 
Deployed with Juju 3.2.3 candidate and Openstack and COS on top of snapped microk8s. 
Some more info in [LP#2033429](https://bugs.launchpad.net/solutions-qa-ci/+bug/2033429)

Wondering if there's any workaround available for us?

**Comment by przemeklal** [comment]
In my most recent deployment, setting up the `monitors` relation was quite fast without the `configurable-scrape-jobs` relation (1-3 seconds per NRPE unit). However, with the `configurable-scrape-jobs` relation in place, it took approx. 50 minutes for each `monitors-relation-joined`/`monitors-relation-changed`.

After removing the  `configurable-scrape-jobs` relation, it returned to the original speed of 1-3 sec per nrpe unit.

However, adding `configurable-scrape-jobs` back took almost 15 hours. I believe this is where the slowness really is.

This cloud consists of physical servers and LXDs. There are 115 NRPE units monitored by cos-proxy in this deployment.

Relevant outputs:
```
15 Nov 2023 14:40:01Z  juju-unit  executing  running monitors-relation-joined hook for nrpe-container/81
15 Nov 2023 14:40:02Z  juju-unit  executing  running monitors-relation-changed hook for nrpe-container/81
15 Nov 2023 14:40:05Z  juju-unit  executing  running monitors-relation-joined hook for nrpe-container/82
15 Nov 2023 14:40:05Z  juju-unit  executing  running monitors-relation-changed hook for nrpe-container/82
15 Nov 2023 14:40:08Z  juju-unit  executing  running monitors-relation-joined hook for nrpe-container/83
15 Nov 2023 14:40:08Z  juju-unit  executing  running monitors-relation-changed hook for nrpe-container/83
15 Nov 2023 14:40:11Z  juju-unit  executing  running monitors-relation-joined hook for nrpe-container/84
15 Nov 2023 14:40:11Z  juju-unit  executing  running monitors-relation-changed hook for nrpe-container/84
15 Nov 2023 14:40:14Z  juju-unit  executing  running monitors-relation-joined hook for nrpe-container/85
15 Nov 2023 14:40:15Z  juju-unit  executing  running monitors-relation-changed hook for nrpe-container/85
15 Nov 2023 14:40:17Z  juju-unit  executing  running monitors-relation-joined hook for nrpe-container/9
15 Nov 2023 14:40:18Z  juju-unit  executing  running monitors-relation-changed hook for nrpe-container/9
15 Nov 2023 14:40:20Z  juju-unit  idle       
15 Nov 2023 14:54:43Z  juju-unit  executing  running downstream-prometheus-scrape-relation-created hook
15 Nov 2023 14:54:43Z  juju-unit  idle       
15 Nov 2023 14:54:44Z  juju-unit  executing  running downstream-prometheus-scrape-relation-joined hook for cos-scrape-interval-config/0
15 Nov 2023 14:54:44Z  workload   blocked    Missing one of (Prometheus|target|nrpe) relation(s)
15 Nov 2023 16:28:15Z  juju-unit  executing  running downstream-prometheus-scrape-relation-changed hook for cos-scrape-interval-config/0
15 Nov 2023 16:28:16Z  juju-unit  idle       
16 Nov 2023 07:47:42Z  workload   active     
```
```
$ juju status --relations | grep cos-proxy-monitors
cos-proxy-monitors                     n/a              active       1  cos-proxy                           latest/edge     48  no       
cos-proxy-monitors/1*                       active    idle   3/lxd/29  <redacted IP>                      
cos-proxy-monitors:downstream-prometheus-scrape                      cos-scrape-interval-config:configurable-scrape-jobs  prometheus_scrape               regular      
nrpe-compute:monitors                                                cos-proxy-monitors:monitors                          monitors                        regular      
nrpe-container:monitors                                              cos-proxy-monitors:monitors                          monitors                        regular      
nrpe-control-node:monitors                                           cos-proxy-monitors:monitors                          monitors                        regular      
nrpe-storage:monitors                                                cos-proxy-monitors:monitors                          monitors                        regular
```

**Comment by simskij** [comment]
We can't really do anything about this unfortunately, as it's a side-effect of the Juju event-model. Our recommendation is to not have a relation between cos-proxy and the upstream COS charms until the proxy has settled, as this significantly reduces the time used.

**Comment by pengwyn** [comment]
We ran into this issue again when upgrading the NRPE charm in one cluster. The problem meant that it took 3 days for the charm hooks to complete. What was worse though, was I tried to help the situation by removing the cos-proxy -> prometheus relation and that didn't take effect until the 3 days were over on the weekend, so we were without monitoring for 1 day.

However, the good news is that I was able to do some debugging by sprinkling print statements throughout the code. It turns out the reason for the slowness is that applying changes to the prometheus relation takes around 3-5s. In one hook, this can be done 100-1000s of times. So I believe I have been able to create a PR that addresses this issue and hopefully brings the time down by an order of magnitude.

I'll submit the PR soon. I realise it might need a complete rework, but I think there is a path forward with this issue.
